### ISSUE TITLE
Yarn from debian cannot run with node from nodesource PPA unless NODE_PATH is set

### ISSUE THREAD

**Issue by soredake** [nodesource/distributions#1141]
Kubuntu 20.10
```
~
❯ yarn
node:internal/modules/cjs/loader:922
  throw err;
  ^

Error: Cannot find module 'babel-runtime/helpers/asyncToGenerator'
Require stack:
- /usr/share/nodejs/yarn/lib/cli/index.js
- /usr/share/nodejs/yarn/bin/yarn.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:15)
    at Function.Module._load (node:internal/modules/cjs/loader:763:27)
    at Module.require (node:internal/modules/cjs/loader:991:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at _load_asyncToGenerator (/usr/share/nodejs/yarn/lib/cli/index.js:17:54)
    at /usr/share/nodejs/yarn/lib/cli/index.js:21:41
    at Object.<anonymous> (/usr/share/nodejs/yarn/lib/cli/index.js:605:3)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/share/nodejs/yarn/lib/cli/index.js',
    '/usr/share/nodejs/yarn/bin/yarn.js'
  ]
}
```
In fish it can be fixed with workaround `set -gx NODE_PATH /usr/lib/nodejs:/usr/share/nodejs`

More info:
https://bugs.launchpad.net/debian/+source/node-yarnpkg/+bug/1899959
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=933229

**Comment by soredake** [comment]
Yarn can now be installed with corepack, which plays nicely with nodejs from this repo, closing.
