### ISSUE TITLE
[ERROR] Node.js 18.17.0 on Ubuntu 22.04 upgrade cannot run create or init

### ISSUE THREAD

**Issue by mythril** [nodesource/distributions#1609]
**Describe your bug**
Cannot use `npm create` or `npm init` with Vue or Svelte (only ones I tested, doubt it has anything to do with them).

**Distribution Information:**
```
$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
**Node Version:**
```
...
1 info using npm@9.6.7
2 info using node@v18.17.0
...
```
**To Reproduce**
```
$ npm init vue@latest
npm ERR! Cannot read properties of undefined (reading 'isStream')

npm ERR! A complete log of this run can be found in: /home/user/.npm/_logs/2023-07-24T00_00_16_324Z-debug-0.log
```

**Expected behavior**
New Vue project is created in the current directory

**Screenshots**
not really applicable, can produce upon request

**Additional context**
```
$ cat /home/user/.npm/_logs/2023-07-24T00_00_16_324Z-debug-0.log
0 verbose cli /usr/bin/node /usr/bin/npm
1 info using npm@9.6.7
2 info using node@v18.17.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/home/user/git/bitbucket.org/fake_user_duh/vue/.npmrc Completed in 0ms
10 timing config:load:project Completed in 3ms
11 timing config:load:file:/home/user/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/usr/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 1ms
15 timing config:load:setEnvs Completed in 0ms
16 timing config:load Completed in 8ms
17 timing npm:load:configload Completed in 8ms
18 timing npm:load:mkdirpcache Completed in 1ms
19 timing npm:load:mkdirplogs Completed in 0ms
20 verbose title npm init vue@latest
21 verbose argv "init" "vue@latest"
22 timing npm:load:setTitle Completed in 1ms
23 timing config:load:flatten Completed in 1ms
24 timing npm:load:display Completed in 2ms
25 verbose logfile logs-max:10 dir:/home/user/.npm/_logs/2023-07-24T00_00_16_324Z-
26 verbose logfile /home/user/.npm/_logs/2023-07-24T00_00_16_324Z-debug-0.log
27 timing npm:load:logFile Completed in 6ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 19ms
31 silly logfile start cleaning logs, removing 1 files
32 timing arborist:ctor Completed in 0ms
33 silly logfile done cleaning log files
34 timing command:init Completed in 16ms
35 verbose stack TypeError: Cannot read properties of undefined (reading 'isStream')
35 verbose stack     at new Body (/usr/lib/node_modules/npm/node_modules/minipass-fetch/lib/body.js:43:18)
35 verbose stack     at new Request (/usr/lib/node_modules/npm/node_modules/minipass-fetch/lib/request.js:51:5)
35 verbose stack     at makeFetchHappen (/usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/index.js:9:19)
35 verbose stack     at doFetch (/usr/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/index.js:108:15)
35 verbose stack     at async RegistryFetcher.packument (/usr/lib/node_modules/npm/node_modules/pacote/lib/registry.js:87:19)
35 verbose stack     at async RegistryFetcher.manifest (/usr/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:23)
35 verbose stack     at async getManifest (/usr/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:30:22)
35 verbose stack     at async missingFromTree (/usr/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:64:22)
35 verbose stack     at async /usr/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:168:32
35 verbose stack     at async Promise.all (index 0)
36 verbose cwd /home/user/git/bitbucket.org/fake_user_duh/vue
37 verbose Linux 5.15.0-76-generic
38 verbose node v18.17.0
39 verbose npm  v9.6.7
40 error Cannot read properties of undefined (reading 'isStream')
41 verbose exit 1
42 timing npm Completed in 143ms
43 verbose code 1
44 error A complete log of this run can be found in: /home/user/.npm/_logs/2023-07-24T00_00_16_324Z-debug-0.log
```

If this is the wrong place to report this, can you point me to the right place?

**Comment by riosje** [comment]
Hi I think @mythril this issue should be directed to the vue team itself.

**Comment by mythril** [comment]
It's not a vue problem, it happens with literally anything that you run npm create or npm init with

**Comment by riosje** [comment]
so, as you mentions is an NPM problem
https://github.com/npm/cli
