### ISSUE TITLE
NPM in nodejs-5.1.0-2nodesource.el7.centos.x86_64 broken

### ISSUE THREAD

**Issue by btd** [nodesource/distributions#179]
Would like to make you know that npm in that package broken:
```
[ec2-user@jenkins ~]$ sudo yum install nodejs
Loaded plugins: auto-update-debuginfo, priorities, update-motd, upgrade-helper
2 packages excluded due to repository priority protections
Resolving Dependencies
--> Running transaction check
---> Package nodejs.x86_64 0:5.1.0-2nodesource.el7.centos will be installed
--> Finished Dependency Resolution

Dependencies Resolved

========================================================================================================================================================================================
 Package                              Arch                                 Version                                                       Repository                                Size
========================================================================================================================================================================================
Installing:
 nodejs                               x86_64                               5.1.0-2nodesource.el7.centos                                  nodesource                               8.1 M

Transaction Summary
========================================================================================================================================================================================
Install  1 Package

Total download size: 8.1 M
Installed size: 28 M
Is this ok [y/d/N]: y
Downloading packages:
nodejs-5.1.0-2nodesource.el7.centos.x86_64.rpm                                                                                                                   | 8.1 MB     00:00     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : nodejs-5.1.0-2nodesource.el7.centos.x86_64                                                                                                                           1/1 
  Verifying  : nodejs-5.1.0-2nodesource.el7.centos.x86_64                                                                                                                           1/1 

Installed:
  nodejs.x86_64 0:5.1.0-2nodesource.el7.centos                                                                                                                                          

Complete!
[ec2-user@jenkins ~]$ node -v
v5.1.0
[ec2-user@jenkins ~]$ npm -v
module.js:340
    throw err;
    ^

Error: Cannot find module 'minimatch'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/rimraf/node_modules/glob/glob.js:44:17)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)

```

**Comment by tsde** [comment]
Hi,
What version of CentOS are you using ? I'm using CentOS 7.1 and node/npm is working just fine
```
# node -v
v5.1.0
# npm -v
3.3.12
```

Can you issue a `which npm` ? Did you have a previous installation of node and/or npm ?

**Comment by btd** [comment]
I am using latest amazon Linux and yes before was 0.10 and 5.0.

Sorry I am not able to check paths for several days.

**Comment by tsde** [comment]
Ok so do you know how you installed the previous (0.10) version ? Was it using CentOS repos, nodesource repos, or manually installed ?

**Comment by btd** [comment]
I always used nodesource's rpm. I downloaded them manually (with ansible to
be clear )
2 Дек 2015 г. 20:23 пользователь "tsde" <notifications@github.com> написал:

**Comment by btd** [comment]
I upgraded to 5.1.1 yesterday and it works.
